language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
install:
  - 'travis_retry bundle install'
notifications:
  email: false
sudo: false
